/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingInquiry {
  'service' : string,
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'phone' : string,
}
export interface GalleryItem {
  'title' : string,
  'description' : string,
  'category' : string,
}
export interface SalonInfo {
  'hours' : string,
  'socialLinks' : Array<string>,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Service {
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
}
export interface Testimonial {
  'date' : Time,
  'name' : string,
  'reviewText' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addGalleryItem' : ActorMethod<[string, string, string, string], undefined>,
  'addService' : ActorMethod<
    [string, string, string, bigint, bigint, string],
    undefined
  >,
  'addTestimonial' : ActorMethod<[string, string, bigint], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<BookingInquiry>>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getSalonInfo' : ActorMethod<[], SalonInfo>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'setSalonInfo' : ActorMethod<
    [string, string, string, string, Array<string>],
    undefined
  >,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];